[project]
name = "bright-website-jupyterbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "feedparser>=6.0.12",
    "jupyter-book>=1.0.4.post1",
    "sphinx-sitemap>=2.9.0",
]
